// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getFeedURL.sql

package database

import (
	"context"
)

const getFeedURL = `-- name: GetFeedURL :one
SELECT id, created_at, updated_at, name, url, user_id FROM feeds WHERE feeds.Url = $1
`

func (q *Queries) GetFeedURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
