// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rmUsers.sql

package database

import (
	"context"
)

const rMUsers = `-- name: RMUsers :exec
DELETE FROM users *
`

func (q *Queries) RMUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, rMUsers)
	return err
}
